### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by wiederm** [wiederm/transformato#65]
The current documentation https://wiederm.github.io/transformato/ does not look like it should (https://johanneskarwou.github.io/transformato/), @wiederm is the correct branch (https://github.com/wiederm/transformato/tree/dev_doc) set in the pages setup? Because it looks like it's only the README from the master branch...

**Comment by wiederm** [comment]
I converted the comment to an issue @JohannesKarwou 

I think I might have found the issue --- it was building from the correct branch but from the `/root` directory. I changed this to `/docs`.
Hopefully, this resolves the issue.

**Comment by JohannesKarwou** [comment]
Perfect! Looks like it should!
