### ISSUE TITLE
Representation issue in README.md

### ISSUE THREAD

**Issue by bbraunsfeld** [wiederm/transformato#78]
The figure [workflow](https://user-images.githubusercontent.com/72743318/166959443-cddda959-8432-4fd9-a836-c9271b4cd2c9.svg) in the README.md is only loaded correctly in the preview. This problem appears in Firefox, Chrom, and Safari as far as I know.

**Comment by wiederm** [comment]
thanks for bringing this to our attention!
We will investigate!

**Comment by JohannesKarwou** [comment]
Good point! I updated the figure and now it should be displayed correctly...
